/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/2026/v1/events/{code}/full/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Full DECODE Specific Event Details
         * @description This returns a complete list of the DECODE specific scores for an event as would be gained by querying all of the separate API routes. This route is intended only to be queried once when a client loads for the purposes of caching the current state. The rate limit on this route and the <code>/api/v2/events/{code}/full/</code> is 4 requests every 30 minutes combined. The point is not for a client to query this route that frequently, but rather to provide some margin of error in case the client must reboot and refresh the cache. This endpoint cannot be hit while a match is in the RANDOMIZED state and will return HTTP <code>503</code> if so. The amount of data returned is very large, about 165kB for a 32 team event.
         */
        get: operations["GetSeasonEventFull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/2026/v1/events/{code}/matches/{match}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the match scoring details.
         * @description DECODE game specific data.
         */
        get: operations["GetSeasonMatchDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/2026/v2/events/{code}/elims/{name}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the match scoring details for an elims match
         * @description DECODE game specific data.
         */
        get: operations["GetElimsSeasonMatchDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets list of events
         * @description A list of all event codes that this instance of the FTCLive server knows about.
         */
        get: operations["GetEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets an event
         * @description A detailed description of an event for any given event code.
         */
        get: operations["GetEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/elim/alliances/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Alliances
         * @description The elimination alliances.
         */
        get: operations["GetAlliances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/matches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Qualification match list
         * @description The Qualification match list for a given event. If matchmaker has not been run when this is requested the match list will be empty.
         */
        get: operations["GetMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/matches/active/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Active Matches
         * @description List of matches currently loaded for play.
         */
        get: operations["GetActiveMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/matches/{number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Qualification Match
         * @description Results for a match that has been played. NO_SUCH_MATCH indicates either an invalid match number or the match has not been played yet.
         */
        get: operations["GetMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/rankings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Rankings
         * @description A list of rankings for the event. Clients should understand that rankings are rather static and schedule
         *     their polling appropriately.
         */
        get: operations["GetRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/rankings/combined/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Rankings Combined
         * @description A list of combined league rankings for all leagues present at an event. Clients should understand that
         *     rankings are rather static and schedule their polling appropriately.
         */
        get: operations["GetRankingsCombined"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/teams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets list of teams competing at an event
         * @description A list of teams defined by team numbers participating in any given event.
         */
        get: operations["GetCompetingTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/teams/{number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets event-specific team info
         * @description Returns a detailed description of a team with a given number competing at a given event. This will
         *     return the team info as it was when the event occurred.
         */
        get: operations["GetEventTeamInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/teamstatus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Team Status
         * @description Returns the team status tracking data. This data should match what appears on the status display. The
         *     status is one of NONE, IN_PROGRESS, FAIL, PASS, READY, LATE, VERY_LATE.
         */
        get: operations["GetTeamStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/wifi/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Team Wifi Assignments
         * @description Returns the list of team wifi channel assignments once it is published.
         */
        get: operations["GetWifiAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{code}/wifi/team/{team}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Team Wifi Assignments
         * @description Returns the wifi assignment for a specific team.
         */
        get: operations["GetTeamWifiAssignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keycheck/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Checks the status of the key requested
         * @description This will immediately return the active status of the specified key.
         */
        get: operations["KeyCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keyrequest/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Requests a key to be granted for an increase rate limit.
         * @description Must include the name of the application making the request by specifying the `name` param in the POST.
         *     This name will be displayed to the scorekeeper to validate the key. This will immediately return a key,
         *     but the key will not be valid until the scorekeeper approves the request. The status of the key can be
         *     checked with /apiv1/keycheck/. Once receiving the key, the application can pass the key as the
         *     Authorization header of the HTTP requests. Once the key is active, the rate limit will be increased for
         *     the specified key.
         */
        post: operations["KeyRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keywait/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Waits until the specified key becomes active.
         * @description This request will return once the scorekeeper has activated the specified key, or immediately if the key is already active.
         */
        get: operations["KeyWait"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets list of teams
         * @description Returns all team numbers that have registered with FIRST as of the last sync to the FIRST registration
         *     database for this release of FTCLive. This is a very long list. Applications that want this data should
         *     query once upon startup and then never again. The packaged team list will always be returned.
         */
        get: operations["GetTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{team}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets a team's info.
         * @description A detailed description of a team for any given team number.
         */
        get: operations["GetTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets the version of the scoring system.
         * @description Returns the version of the scoring system software.
         */
        get: operations["Version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/events/{code}/awards/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Awards
         * @description List of award winners that have been presented. The list changes as awards are <em>presented</em>. Award
         *     winners are shown in this list once they have been publicly presented. For individual awards, the team
         *     affiliation may or may not be included. For most awards, the winner is series=1, second place is 2,
         *     third place is 3.
         */
        get: operations["GetAwards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/events/{code}/elims/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets All Elims
         * @description Returns an array of all elimination matches currently scheduled. Does not return all possible matches,
         *     only those that are guaranteed to occur.
         */
        get: operations["GetElimsMatchesV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/events/{code}/elims/{name}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Elimination Match
         * @description Results for a match that has been played. NO_SUCH_MATCH indicates either an invalid match number or the
         *     match has not been played yet.
         */
        get: operations["GetElimMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/events/{code}/full/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gets Full Event Details
         * @description This returns a complete snapshot of the event as would be gained by querying all of the separate API
         *     routes. This route is intended only to be queried once when a client loads for the purposes of caching
         *     the current state. The rate limit on this route and the `/api/{season}/v1/events/{code}/full/`
         *     is 4 requests every 30 minutes combined. The point is not for a client to query this route that
         *     frequently, but rather to provide some margin of error in case the client must reboot and refresh the
         *     cache. This endpoint cannot be hit while a match is in the RANDOMIZED state and will return HTTP
         *     `503` if so. The amount of data returned is very large, about 75kB for a 32 team event.
         */
        get: operations["GetEventFull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/stream/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * (Websocket Only) Match Event Stream
         * @description Connects a websocket to listen for match events. Events come as messages on the socket in near-real-time
         *     to when they occur. Each event has a timestamp in millis. Notable events are MATCH_LOAD, MATCH_START,
         *     MATCH_COMMIT, MATCH_POST, and MATCH_ABORT. The message only contains minimal data about the match
         *     involved. ApiV1 HTTP endpoints can be hit to get more details about the match.
         *     Note: The Swagger 'Try it out' feature does not support Websockets.
         */
        get: operations["MatchEventStream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StackTraceElement: {
            fileName?: string;
            /** Format: int32 */
            lineNumber: number;
            moduleName?: string;
            moduleVersion?: string;
            classLoaderName?: string;
            className?: string;
            methodName?: string;
            nativeMethod: boolean;
        };
        Throwable: {
            message?: string;
            localizedMessage?: string;
            cause?: components["schemas"]["Throwable"];
            stackTrace?: components["schemas"]["StackTraceElement"][];
            ourStackTrace?: components["schemas"]["StackTraceElement"][];
            suppressed?: components["schemas"]["Throwable"][];
        };
        /** @enum {string} */
        Status: "NONE" | "IN_PROGRESS" | "FAIL" | "PASS" | "READY" | "LATE" | "VERY_LATE";
        ApiV1ActiveMatchList: {
            matches?: components["schemas"]["ApiV1MatchBrief"][];
        };
        ApiV1ElimsAlliance: {
            /** Format: int32 */
            seed: number;
            /** Format: int32 */
            captain: number;
            /** Format: int32 */
            pick1: number;
            /** Format: int32 */
            pick2: number;
            dq: boolean;
        };
        ApiV1ElimsAllianceList: {
            alliances?: components["schemas"]["ApiV1ElimsAlliance"][];
        };
        ApiV1ElimsMatch: {
            match?: string;
            red?: components["schemas"]["ApiV1ElimsAlliance"];
            blue?: components["schemas"]["ApiV1ElimsAlliance"];
            /** Format: int64 */
            time: number;
        };
        ApiV1ElimsMatchList: {
            matchList?: components["schemas"]["ApiV1ElimsMatch"][];
        };
        ApiV1Error: {
            message?: string;
            localizedMessage?: string;
            cause?: components["schemas"]["Throwable"];
            stackTrace?: components["schemas"]["StackTraceElement"][];
            suppressed?: components["schemas"]["Throwable"][];
            errorCode?: components["schemas"]["ErrorCodes"];
        };
        /** @enum {string} */
        ErrorCodes: "REJECT_REQUEST" | "TOO_MANY_REQUESTS" | "NOT_READY" | "NO_PERMS" | "NO_SUCH_EVENT" | "NO_SUCH_MATCH" | "NO_SUCH_TEAM" | "NO_SUCH_YEAR" | "NO_NAME" | "NO_SUCH_KEY" | "NO_SUCH_ROUTE" | "UNKNOWN_ERROR";
        ApiV1Event: {
            eventCode?: string;
            name?: string;
            type?: string;
            status?: string;
            finals: boolean;
            /** Format: int32 */
            division: number;
            /** Format: int64 */
            start: number;
            /** Format: int64 */
            end: number;
            /** Format: int32 */
            fieldCount: number;
        };
        ApiV1EventList: {
            eventCodes?: string[];
        };
        ApiV1Key: {
            name?: string;
            key?: string;
            /** Format: int64 */
            startTime: number;
        };
        ApiV1KeyStatus: {
            active: boolean;
        };
        ApiV1MatchBrief: {
            matchName?: string;
            /** Format: int32 */
            matchNumber: number;
            /** Format: int32 */
            field: number;
            /** @description ApiV1QualsAlliance if this match is a qualification match or ApiV1ElimsAlliance if this match is an eliminations match. */
            red?: components["schemas"]["ApiV1QualsAlliance"] | components["schemas"]["ApiV1ElimsAlliance"];
            /** @description ApiV1QualsAlliance if this match is a qualification match or ApiV1ElimsAlliance if this match is an eliminations match. */
            blue?: components["schemas"]["ApiV1QualsAlliance"] | components["schemas"]["ApiV1ElimsAlliance"];
            finished: boolean;
            matchState?: string;
            /**
             * Format: int64
             * @description If the matchState is COMMITTED then this is the time of the most recent commit. Otherwise, this is the time that the match schedule was created.
             */
            time: number;
        };
        ApiV1MatchDetailed: {
            matchBrief?: components["schemas"]["ApiV1MatchBrief"];
            /** Format: int64 */
            startTime: number;
            /** Format: int64 */
            scheduledTime: number;
            /** Format: int64 */
            resultPostedTime: number;
            /** Format: int32 */
            redScore: number;
            /** Format: int32 */
            blueScore: number;
            red?: components["schemas"]["ApiV1ScoreBreakdown"];
            blue?: components["schemas"]["ApiV1ScoreBreakdown"];
            /** Format: int32 */
            randomization: number;
        };
        ApiV1MatchDetailedList: {
            matches?: components["schemas"]["ApiV1MatchDetailed"][];
        };
        ApiV1MatchList: {
            matches?: components["schemas"]["ApiV1MatchBrief"][];
        };
        ApiV1QualsAlliance: {
            /** Format: int32 */
            team1: number;
            /** Format: int32 */
            team2: number;
            isTeam1Surrogate: boolean;
            isTeam2Surrogate: boolean;
        };
        ApiV1Ranking: {
            /** Format: int32 */
            team: number;
            teamName?: string;
            /** Format: int32 */
            ranking: number;
            /**
             * Format: int32
             * @description only populated at league meets
             */
            leagueRanking: number;
            /** @description the formatted decimal average Ranking Points */
            rankingPoints?: string;
            /** @description the formatted decimal average TBP1 */
            tbp1?: string;
            /** @description the formatted decimal average TBP2 */
            tbp2?: string;
            /** @description the formatted decimal average TBP3 */
            tbp3?: string;
            /** Format: int32 */
            matchesPlayed: number;
            /**
             * Format: int32
             * @description Not populated for DECODE
             */
            highestScore: number;
            /** Format: int32 */
            wins: number;
            /** Format: int32 */
            losses: number;
            /** Format: int32 */
            ties: number;
        };
        ApiV1RankingList: {
            rankingList?: components["schemas"]["ApiV1Ranking"][];
        };
        ApiV1ScoreBreakdown: {
            /** Format: int32 */
            auto: number;
            /** Format: int32 */
            teleop: number;
            /** Format: int32 */
            end: number;
            /** Format: int32 */
            penalty: number;
            /** @description true if team 1 is a No-Show or receives a Red Card */
            dq1: boolean;
            /** @description true if team 2 is a No-Show or receives a Red Card */
            dq2: boolean;
            /** Format: int32 */
            robot1: number;
            /** Format: int32 */
            robot2: number;
        };
        ApiV1StatusList: {
            activeStatusTypes?: components["schemas"]["ApiV1StatusType"][];
            teamStatusList?: components["schemas"]["ApiV1TeamStatus"][];
        };
        ApiV1StatusType: {
            id?: string;
            abbreviation?: string;
            name?: string;
        };
        ApiV1Team: {
            /**
             * Format: int32
             * @description The team's number
             */
            number: number;
            /** @description The team's nickname */
            name?: string;
            /** @description The team's school or affiliation */
            school?: string;
            /** @description The team's home city */
            city?: string;
            /** @description The team's home state */
            state?: string;
            /** @description The team's home country */
            country?: string;
            /**
             * Format: int32
             * @description The team's rookie year
             */
            rookie: number;
        };
        ApiV1TeamDetailedList: {
            teams?: components["schemas"]["ApiV1Team"][];
        };
        ApiV1TeamList: {
            teamNumbers?: number[];
        };
        ApiV1TeamStatus: {
            /** Format: int32 */
            team: number;
            status?: {
                [key: string]: components["schemas"]["Status"];
            };
        };
        ApiV1Version: {
            version?: string;
        };
        ApiV1WifiAssignment: {
            /** Format: int32 */
            team: number;
            /** Format: int32 */
            assignment24?: number;
            /** Format: int32 */
            assignment5?: number;
        };
        ApiV1WifiAssignmentList: {
            assignments?: components["schemas"]["ApiV1WifiAssignment"][];
        };
        ApiV2Award: {
            name?: string;
            isTeamAward: boolean;
            winners?: components["schemas"]["ApiV2AwardAssignment"][];
        };
        ApiV2AwardAssignment: {
            /** @description The name of the winner of an individual award. */
            name?: string;
            /**
             * Format: int32
             * @description The place of this assignment. 1 = 1<sup>st</sup>, etc. For non-ordered awards, this is the order the names were entered.
             */
            series: number;
            /**
             * Format: int32
             * @description The winning team of the award, or the team the individual is affiliated with.
             */
            team: number;
        };
        ApiV2AwardList: {
            awards?: components["schemas"]["ApiV2Award"][];
        };
        ApiV2FullEvent: {
            version?: components["schemas"]["ApiV1Version"];
            event?: components["schemas"]["ApiV1Event"];
            teamList?: components["schemas"]["ApiV1TeamDetailedList"];
            teamStatusInfo?: components["schemas"]["ApiV1StatusList"];
            rankingsList?: components["schemas"]["ApiV1RankingList"];
            combinedRankingsList?: components["schemas"]["ApiV1RankingList"];
            matchList?: components["schemas"]["ApiV1MatchDetailedList"];
            allianceList?: components["schemas"]["ApiV1ElimsAllianceList"];
            elimsMatchList?: components["schemas"]["ApiV1ElimsMatchList"];
            elimsMatchDetailedList?: components["schemas"]["ApiV1MatchDetailedList"];
            awardList?: components["schemas"]["ApiV2AwardList"];
        };
        ApiV2Update: {
            /** Format: int64 */
            updateTime: number;
            updateType?: components["schemas"]["ApiV2UpdateType"];
            payload?: components["schemas"]["ApiV2UpdateMatchPayload"];
        };
        ApiV2UpdateMatchPayload: {
            /** Format: int32 */
            number: number;
            shortName?: string;
            /** Format: int32 */
            field: number;
        };
        /** @enum {string} */
        ApiV2UpdateType: "MATCH_LOAD" | "MATCH_START" | "MATCH_ABORT" | "MATCH_COMMIT" | "MATCH_POST" | "SHOW_PREVIEW" | "SHOW_RANDOM" | "SHOW_MATCH" | "INIT_SUBMITTED";
        ApiSeasonSpecificMatchDetailed: {
            matchBrief?: components["schemas"]["ApiV1MatchBrief"];
            /** Format: int64 */
            startTime: number;
            /** Format: int64 */
            scheduledTime: number;
            /** Format: int64 */
            resultPostedTime: number;
            /** Format: int32 */
            redScore: number;
            /** Format: int32 */
            blueScore: number;
            red?: components["schemas"]["ApiV1ScoreBreakdown"];
            blue?: components["schemas"]["ApiV1ScoreBreakdown"];
            /** Format: int32 */
            randomization: number;
        };
        ApiSeasonSpecificMatchDetailedList: {
            matches?: components["schemas"]["ApiSeasonSpecificMatchDetailed"][];
        };
        ApiV1FullSeasonSpecificEvent: {
            matchList?: components["schemas"]["ApiSeasonSpecificMatchDetailedList"];
            elimsMatchList?: components["schemas"]["ApiSeasonSpecificMatchDetailedList"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSeasonEventFull: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1FullSeasonSpecificEvent"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description This request cannot be completed because a match is about to start. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetSeasonMatchDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
                /** @description The match number */
                match: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSeasonSpecificMatchDetailed"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetElimsSeasonMatchDetails: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
                /** @description The match name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSeasonSpecificMatchDetailed"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description Eliminations not started */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1EventList"];
                };
            };
        };
    };
    GetEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Event"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetAlliances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1ElimsAllianceList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description Event not yet in eliminations */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetMatches: {
        parameters: {
            query?: never;
            header?: {
                /** @description GMT time of last hit */
                "If-Modified-Since"?: string;
            };
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Last update time of any match in this list */
                    "Last-Modified"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1MatchBrief"];
                };
            };
            /** @description No changes since last hit */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetActiveMatches: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1ActiveMatchList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetMatch: {
        parameters: {
            query?: never;
            header?: {
                /** @description GMT time of last hit */
                "If-Modified-Since"?: string;
            };
            path: {
                /** @description The event code */
                code: string;
                /** @description The match number */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Last update time of any match in this list */
                    "Last-Modified"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1MatchDetailed"];
                };
            };
            /** @description No changes since last hit */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Event or Match not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetRankings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1RankingList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetRankingsCombined: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1RankingList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetCompetingTeams: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1TeamList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetEventTeamInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
                /** @description The team's number */
                number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Team"];
                };
            };
            /** @description No such team or event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetTeamStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1StatusList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetWifiAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1WifiAssignmentList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description Wifi assignments not published */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetTeamWifiAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
                /** @description The team number */
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1WifiAssignment"];
                };
            };
            /** @description No such or team event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description Wifi assignments not published */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    KeyCheck: {
        parameters: {
            query?: never;
            header: {
                /** @description The key to check the status of. */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1KeyStatus"];
                };
            };
            /** @description Key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    KeyRequest: {
        parameters: {
            query: {
                /** @description The name of the program requesting the key. */
                name: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Key"];
                };
            };
            /** @description Must include `name` as a parameter to be displayed to the scorekeeper */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    KeyWait: {
        parameters: {
            query?: never;
            header: {
                /** @description The key to wait until it is valid for. */
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1KeyStatus"];
                };
            };
            /** @description Key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1TeamList"];
                };
            };
        };
    };
    GetTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The team number */
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Team"];
                };
            };
            /** @description Team not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    Version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Version"];
                };
            };
        };
    };
    GetAwards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV2AwardList"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetElimsMatchesV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1MatchList"];
                };
            };
            /** @description Eliminations not started */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetElimMatch: {
        parameters: {
            query?: never;
            header?: {
                /** @description GMT time of last hit */
                "If-Modified-Since"?: string;
            };
            path: {
                /** @description The event code */
                code: string;
                /** @description The match name (in lowercase) */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    /** @description Last commit time of this match, or matchmaker run time. */
                    "Last-Modified"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1MatchDetailed"];
                };
            };
            /** @description No changes since last hit */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description Eliminations not started */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    GetEventFull: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The event code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV2FullEvent"];
                };
            };
            /** @description No such event */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
            /** @description This request cannot be completed because a match is about to start. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV1Error"];
                };
            };
        };
    };
    MatchEventStream: {
        parameters: {
            query: {
                /** @description The event code */
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiV2Update"];
                };
            };
        };
    };
}
